---
title: "Mid-course reflection (SR #2)"
subtitle: "Assigned Mon 02/03/2025 | Due Sat 02/08/2025"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
---

## Description 

In this assignment, you'll be writing about your learning throughout this course so far. Remember that these assignments are opportunities for you to reflect on your own progress in the course. 

Reread your responses to your Pre-course reflection (SR #1) to refresh your memory, then answer the following questions:

- [ ] **1.** How have you progressed towards your learning goals for this course? 
- [ ] **2.** What skills are you proud of developing? 
- [ ] **3.** If you've needed help, how have you sought it out? If you haven't sought out help, why not?
- [ ] **4.** Looking forward, how have your learning goals changed? Have they stayed the same? 
- [ ] **5.** What topics have excited you the most (so far)? Have you spent time or efforts outside of class and / or the assignments diving deeper into any of these topics? If yes, what did you learn?
- [ ] **6.** How would you change the structure of this course, if at all? If you wouldn't, what in particular has been working for you?
- [ ] **7.** Is there anything about this course that you are really enjoying? Anything that isn't working for you? 
- [ ] **8.** What else would you like me to know about your experience in the course thus far? 

## Rubric (specifications)

You must complete the following, as detailed below, to receive a "Satisfactory" mark for this Mid-course reflection:

[**Complete the following steps in your GitHub Classroom repo (`eds240-sr2-username/SR2-midcourse-reflection.qmd`):**]{.teal-text}

  - [ ] Include your preferred name in the `author` field of the `SR2-precourse-reflection.qmd` YAML. 
  - [ ] Answer all 8 questions, above. There is no set length requirement, but you must answer each question in full to receive a Satisfactory score.
  - [ ] Push `SR2-midcourse-reflection.qmd` to GitHub using GitHub Classrooms by 11:59pm PT on Sat 02/03/2025
