---
title: "End-of-course reflection (SR #3)"
subtitle: "Assigned Mon 03/10/2025 | Due Sat 03/15/2025"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
---

## Description 

In this assignment, you'll reflect on your learning throughout this class. Revisit your self-reflections from the start and middle of the quarter, then answer the following questions:

- [ ] **1.** Since your mid-quarter self-reflection, have you improved any of your existing skills? Have you learned new ones?
- [ ] **2.** Have you accomplished your learning goals for this quarter (that you set in SR #1, and potentially expanded upon / modified in SR #2)? If you did, how did you do it?
- [ ] **3.** What are you proudest of accomplishing in this course? 
- [ ] **4.** What are some transferable skills that you developed in this course? How might you apply them to other courses / deliverables within your graduate program (e.g. MEDS, MESM, etc.) or to jobs in the future?
- [ ] **5.** What is one thing that you really liked about this course, and why? What is one thing you think could be improved about this course, and how?
- [ ] **6.** Is there anything else you'd like the instructors to know about your experience in the course?

## Rubric (specifications)

You must complete the following, as detailed below, to receive a "Satisfactory" mark for this End-of-course reflection:

**Complete the following steps in your GitHub Classroom repo (`eds240-sr3-username/SR3-endcourse-reflection.qmd`):**

- [ ] Include your preferred name in the `author` field of the `SR3-endcourse-reflection.qmd` YAML. 
- [ ] Answer all 6 questions, above. There is no set length requirement, but you must answer each question in full to receive a Satisfactory score.
- [ ] Push `SR3-endcourse-reflection.qmd` to GitHub using GitHub Classrooms by 11:59pm PT on Sat 03/15/2025.

*Additionally, please complete the formal UCSB course evaluations for both the EDS 240 instructor (Sam Csik) and TA (Sloane Stephenson) by the deadline (Friday, 03/14/2025).*
