---
format: 
  revealjs:
    slide-number: true
    # code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - ../meds-slides-styles.scss
editor_options: 
  chunk_output_type: console
---

## {#title-slide data-menu-title="Title Slide" background="#053660"} 

[EDS 240: Lecture 4.1]{.custom-title}

[*Visualizing relationships*]{.custom-subtitle}

<hr class="hr-teal">

[Week 4 | January 29^th^, 2024]{.custom-subtitle3}

---

Visualizing data *relationships*?

to study a relationship between two numeric variables

can also view by a group (categorical variable)
sometimes with a third numeric variable (points = size e.g. bubble plot)
  - not generally recommended
    - encoding the same type of variable (numeric) on two different scales: position & size
    - hard to compare strengths of different associations
    - much easier to perceive diffferences when encoded by position rather than size
    - hard to see small differences in size
    - difficult to match scale of circle size to scale of difference

---

When samples size is large, overplotting can disguise trends

strategies for dealing: 
- use smaller points and/or transparency
- add color by group
- add jittering
- add a rug plot or marginal density plot
- create a hexbin

<!-- --- -->

<!-- scatter plot -->
<!-- fitting linear models & smoothers (e.g. lowess) -->
<!-- correlation matrix / heat map -->
<!-- parallel coordinates plot -->
<!-- data transformation (e.g log10) -->
<!-- see culment depth & culment length scatter plot: https://www.kaggle.com/code/florianspire/palmer-penguins-data-preprocessing-and-analysis -->

<!-- --- -->

<!-- https://www.tylervigen.com/spurious-correlations -->

---

looking forward

- sankey
- choropleth
- {geopfacet}
- heatmaps
- parallel coordinate plots
- treemap
- sunburst
- radar plots

---

##  {#end-break data-menu-title="# Break #" background="#047C90"}

<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">{{< fa mug-hot title="a mug with steam rising out the top" >}} Take a Break</p>
<p class="caption-text">*~ This is the end of Lesson 2 (of 4) ~*</p>
</div>

```{r}
countdown::countdown(
  minutes = 5,
  # left = 0, right = 0,
  # Fanfare when it's over
  play_sound = TRUE,
  color_border              = "#FFFFFF",
  color_text                = "#7aa81e",
  color_running_background  = "#7aa81e",
  color_running_text        = "#FFFFFF",
  color_finished_background = "#ffa07a",
  color_finished_text       = "#FFFFFF",
  font_size = "2em",
  )
```
