---
format: 
  revealjs:
    slide-number: true
    # code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - ../meds-slides-styles.scss
editor_options: 
  chunk_output_type: console
---

## {#title-slide data-menu-title="Title Slide" background="#053660"} 

[EDS 240: Lecture 3.1]{.custom-title}

[*Choosing the right graphic form*]{.custom-subtitle}

<hr class="hr-teal">

[Week 3 | January 22^nd^, 2024]{.custom-subtitle3}

---

"How do you know that you have chosen the right graphic form to represent your data?"

Cairo: "If I had the answer to that, I'd be rich by now...I have no idea, but I can give you some clues to make your own choices based on what we know about why and how visualization works"

---

why visualizing data is important

Richard Thayler example of grading 0-100 vs 1-137

takeaway: vision is our most developed sense! Mapping data into visual properties is powerful

---

An example: 

compare unemployment figures of 5 countries (A, B, C, D, E)

mapping = choosing properties that will let readers accurately compare unemployment figures without having to read all the numbers. 

Several ways to encode (show fig 5.2)

LENGHT, HEIGHT, POSITION probably the best (have students discuss)

---

Suggestions (by Albert Cairo)

1. **Think about the task(s) you want to enable or message(s) you want to convey.** For example, do you want to compare, see change or flow, reveal relationships or connections, envision temporal or spatial patterns.

2. **Try different graphic forms,** especially if you have more than one task to enable or message to convey.

3. **Arrange the components of the graphic** to make it as easy as possible to extract meaning from your graphic quickly

4. **Test the outcomes of your graphic on others,** particularly on those who are representative of the audience you are trying to reach

---

## {#choosing-graphic-form data-menu-title="Choosing a graphic form"} 

---

## {#choosing-graphic-form data-menu-title="Choosing a graphic form"} 

[Choosing the right chart type depends on:]{.slide-title}

<hr>

<br>

. . . 

::: {.center-text}
[**how many variables *and* how many data points you need to visualize**]{.body-text-m .teal-text}  

**(e.g. several vs. many data points; number of categorical and/or numeric variables)**
:::

<br>

. . .

::: {.center-text}
[**what you would like to show**]{.body-text-m .teal-text} 

**(e.g. comparisons, relationships, distributions, compositions)**
:::

<br>

. . . 


::: {.center-text}
[**the data types you want to visualize**]{.body-text-m .teal-text}  

**(e.g. numeric, categorical, spatial, time series, network; ordered / not ordered)**
:::

---

tools for choosing a grpahic form

- from data to viz: <https://www.data-to-viz.com/>
- the data visualization catalogue: <https://datavizcatalogue.com/>

---

hierarchy of elementary perceptual tasks (methods of encoding) by William S. Cleveland & Robert McGill <https://www.tandfonline.com/doi/pdf/10.1080/01621459.1984.10478080?casa_token=6UivYaSxb10AAAAA:kpW03CXnGTnbtz1lvU9M8SBvSl5SHpcKFHWdV9jsNTl-LtRK9X9eUb0HUhPOcFJbgM8cQZc4CVef>

[put Cairo's version here]

a viewer performs one or more of these mental-visual tasks to extract the values of real variables represented on most graphs


"If you wish to create a successful chart, you need to construct it based on elementary tasks 'as high in the hierarchy as possible'"

---

exercise:

have students estiamate pie slices
have students estimate bar lengths

---

caveats to Cleveland & McGill

1. they were writign about just statistical charts -- what about data maps that rely on area / shading / hue? -- these lower scale mehtods may be appropriate when the goal isnt' to enable accurate judgements to reveal general patterns

e.g. choropleth map; but what if we want to compare unemployment rates between counties? pick a graphcial form from the top of the scale then (e.g. bar chart)

what if we want to show readers both big picture and details? use both! **multiple graphic forms may enable multiple tasks**

2. you can't apply anyone's method (including Cleveland & McGill) of choosing graphic forms uncritically

e.g. Sankey diagram
e.g. stacked area chart using Europe's GDP (can use CA drought as example here next??) -- goal is to compare Europe to rest of continents; if goal is to cmpare all continents in same manner, a time series / line chart would be better
e.g. show parts of a whole and all lines as individual entities -- use interactivity?

---

plot data directly

e.g. plot income and expenses as separate lines or just plot a singe net income line? (latter) **plot your data directly, if difference matters more, plot the difference!** (need environmental example here)

---

SOME TIPS

- baselines
- breaking up plots when data vary so much that presenting them all on a single chart renders it useless (e.g. use fracking data?)
- ordering variables / categories -- e.g. see trends across age groups by grouping bars by media (see pg 139) (NEED EDS EXAMPLE HERE)

--- 

use logical & meaningful baselines

- bar, lollipops, histograms, etc should always have a 0 baseline -- cannot truncate when main visual cue is height/length measured from a common baseline
- scatterplot, line graph, ec. -- can be okay to truncate axes since main visual cue is position, not height/length

---

## {#from-data-to-viz2 data-menu-title="From Data to Viz" background-iframe="https://www.data-to-viz.com/" background-interactive=true}

::: footer
**<https://www.data-to-viz.com/>**
:::

---

## {#tbd data-menu-title="tbd"} 

[tbd]{.slide-title}

<hr>

We'll review some fundamental chart types -- many others are variants or extensions on these

This list is not exhaustive


