---
title: "Pre-course reflection (SR #1)"
subtitle: "Assigned Mon 01/08/2024 | Due Sat 01/13/2024"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
---

## Description 

In this assignment, you’ll introduce yourself, come up with a plan for what you’d like to get out of the class, and roughly outline how you'll accomplish your goals throughout the quarter. You’ll continue visiting the goals you set for yourself in this assignment throughout the quarter, so it’s worthwhile to be reflective!

Because everyone is participating under unique circumstances, I want to learn about your learning contexts. I can best support you in this class if you address the following:

1. [**Some questions about school and life:**]{.teal-text}  

    - [ ] Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I’ve been working in industry X for Y years”) [**(1-2 sentences)**]{.peach-text}
    - [ ] What do you hope to get out of this class? [**(3-4 sentences)**]{.peach-text}
    - [ ] If you have a particular career goal in mind, how does this course apply to your future career, if at all? [**(1-3 sentences)**]{.peach-text}
    - [ ] What do you wish your instructors knew about you, but don’t? [**(2-4 sentences)**]{.peach-text}

2. [**Some questions about the way you like to learn:**]{.teal-text}   

    - [ ] What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them? [**(4-5 sentences)**]{.peach-text}
    - [ ] How confident do you feel in your data visualization skills? Why? [**(3-4 sentences)**]{.peach-text}
    - [ ] How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why? [**(3-4 sentences)**]{.peach-text}
    - [ ] What have you struggled with in the past in other graduate-level courses? Why? [**(3-4 sentences)**]{.peach-text}
    - [ ] Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding? [**(1-2 sentences)**]{.peach-text}
    - [ ] What responsibilities do you have outside of school, and how do you want to balance them? [**(3-4 sentences)**]{.peach-text}
    - [ ] Which learning goals from the syllabus are you most excited about? [**(3-4 sentences)**]{.peach-text}
    - [ ] **Most importantly**, how do you plan on accomplishing your learning goals for this course? **Note:** be specific here! Instead of writing, “I will complete homework assignments” or “I will study”,  you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc. [**(5-8 sentences)**]{.peach-text}

3. [**Some fun questions:**]{.teal-text}  

    - [ ] What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy? [**(3-5 sentences)**]{.peach-text}
    - [ ] What is a piece of media you enjoyed recently? (e.g. music, book, movie, tweet, meme) [**(2-4 sentences)**]{.peach-text}

## Rubric (specifications)

You must complete the following, as detailed below, to receive a "Satisfactory" mark for this Pre-course reflection:

**Complete the following steps in your GitHub Classroom repo (`eds240-sr1-username/SR1-precourse-reflection.qmd`):**

  - [ ] include your preferred name, and if you feel comfortable, your preferred pronouns in the `author` field of the `SR1-precourse-reflection.qmd` YAML 
  - [ ] answer all questions above, adhering to the length requirements specified at the end of each question prompt
  - [ ] we (your instructors) should be able to successfully render `SR1-precourse-reflection.qmd` locally without error, *however* **do not push any html files to GitHub** (i.e. `SR1-precourse-reflection.html` and `SR1-precourse-reflection_files/`; consider adding these to your `.gitignore` so that you don't accidentally push them)
  - [ ] push your completed `SR1-precourse-reflection.qmd` to GitHub via GitHub Classrooms by 11:59pm PT on Sat 01/13/2024

<!-- <br> -->

<!-- ::: {.center-text .body-text-m} -->
<!-- **GitHub Classroom URL: <https://classroom.github.com/a/t8oAcbbP>** -->
<!-- ::: -->
