---
title: "End-of-course reflection (SR #3)"
subtitle: "Assigned Mon 03/11/2024 | Due Sat 03/16/2024"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
title-block-banner: true
---

## Description 

In this assignment, you’ll reflect on your learning throughout this class. Revisit your self-evaluations from the start and middle of the quarter,  and answer the following questions in [**2-6 sentences**]{.peach-text} each:

- [ ] Since your mid-quarter self-evaluation, have you improved any of your existing skills? Have you learned new ones?
- [ ] Have you accomplished your learning goals for this quarter (that you set at the beginning of the quarter)? If you did, how did you do it?
- [ ] What are you proudest of accomplishing in this course? 
- [ ] What are some transferable skills that you developed in this course? How might you apply them to other courses / deliverables within your graduate program (e.g. MEDS, MESM, etc.) or to jobs in the future?
- [ ] What is one thing that you really liked about this course, and why? What is one thing you think could be improved about this course, and how?
- [ ] Is there anything else you’d like the instructors to know about your experience in the course?


## Rubric (specifications)

You must complete the following, as detailed below, to receive a "Satisfactory" mark for this End-of-course reflection:

**Complete the following steps in your GitHub Classroom repo (eds240-SR3/SR3-endcourse-reflection.qmd):**

- [ ] include your preferred name, and if you feel comfortable, your preferred pronouns in the `title` of the `SR3-endcourse-reflection.qmd` YAML 
- [ ] address each question in at least 2-6 sentences (but please feel free to expand on any of these, if you'd like)
- [ ] push `SR3-endcourse-reflection.qmd` to GitHub using GitHub Classrooms by 11:59pm PT on Sat 03/16/2024

Additionally, please complete the ESCI evaluations associated with this course (EDS 240) for both the instructor (Sam Csik) and TA (Sevan Esaian) by the deadline (Friday, 03/15/2024).
